# Page settings

baseurl = "http://it-boyer.github.io/iMe/docs"
languageCode = "en-us"
defaultContentLanguage = "en"
theme = "almeida-cv"
title = "Example - CV"

# 发布目录，指向github的本地仓库
publishdir = "docs"

# 编译草稿，使用改参数保证hugo server即使没有加`--buildDrafts`，也能访问draft=true的md
buildDrafts = true

[params]
colorDark = "#666"
colorLight = "#fff"
colorPageBackground = "#ddd"
colorPrimary = "#e3bfb8"
colorPrimaryText = "#fff"
colorRightColumnBackground = "#f5f5f5"
colorSecondary = "#aaa"
pages = 1
